language: python
python:
  - "3.6.8"
install:
  - python -m pip install poetry
  - python -m pip install flake8
  - python -m pip install -U pytest
script:
  - make lint
  - make test
  # pip install -r requirements.txt
